apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:  
  replicas: 3 
  selector:
    matchLabels:
      app: orderlabel
  template:
    metadata:
      labels:
        app: orderlabel
    spec:
      containers:
      - name: orderapi
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
#Service config
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: orderlabel
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 80
        
